import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { CldUploadButton } from "next-cloudinary";

export default function Home() {
  const handleUpload = (result, widget) => {
    console.log(result.info.url);
  };
  const handleError = (error, widget) => {
    console.log(error);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Hello</p>
        <CldUploadButton
          uploadPreset="hackathon"
          onUpload={handleUpload}
          onError={handleError}
        />
      </main>
    </>
  );
}
